### ISSUE TITLE
Login only works with reverse proxy

### ISSUE THREAD

**Issue by Alistair1231** [vincentbitter/koreader-calibre-web-sync#2]
I got an error like "unknown server error" or something like that in koreader. The docker logs showed nothing.

For troubleshooting I tried curl before/after setting up a reverse proxy to point to the container.
For the tests I urlencoded the username part.
![image](https://github.com/vincentbitter/koreader-calibre-web-sync/assets/26165288/f08c1f3b-99f0-43ff-a480-db6fb98a01b6)

**Comment by vincentbitter** [comment]
I am using a reverse proxy in production, but during development I connected directly to my instance. So, "it should work".

The 404 is fine, as there is no page served on the root. If you append "/swagger/index.html" to the URL, you hopefully will get content of the API definition. I don't see the response of your curl command to the reverse proxy, but given the red arrow, it looks like an error? So, I guess your reverse proxy is setup wrong?
