### ISSUE TITLE
Sync and ePub Reader Suggestions

### ISSUE THREAD

**Issue by mrjfilippo** [vincentbitter/koreader-calibre-web-sync#3]
Browser: Firefox 
OS: Android 14 and Windows 11

I hope to be able to use calibre-web-automated in conjunction with my phone. I noticed progress doesn't sync when I read with the built-in epub reader on either device. On Windows, progress seems to be locally saved. On Android, no progress is saved.

Moreover, on mobile, the epub doesn't use all the available space.

<img src="https://github.com/user-attachments/assets/45ae4c4b-1b67-4170-94c1-a8dc5336e484" width="200" height="400">

Additional suggestions for the epub reader would be a search function, notes, and highlights.

Is there another setup I missed that could achieve this?

Thanks for keeping calibre-web alive and adding features!

**Comment by vincentbitter** [comment]
Sorry, you've reported in the wrong repo. Please check the caliber-web repo and report your issue there. Thank you!
