### ISSUE TITLE
Does this sync progress between Koreader clients?

### ISSUE THREAD

**Issue by cstby** [vincentbitter/koreader-calibre-web-sync#4]
I read through the Readme, and I'm not clear on whether this functions as a Koreader sync server in addition to updating the "read" status in Calibre Web.

**Comment by vincentbitter** [comment]
Hi, thanks for your interest in the project. Unfortunately, it does not capture and store the progress (%), so it only marks the books as ‘read’ in Calibre-web. Calibre-web does not provide a field to store the progress, making it hard to provide such feature.
